---
- name: Configure web server to forward http request toward pinnwand web server
  ansible.builtin.template:
    src: virtual_host_pinnwand.conf.j2
    dest: /etc/httpd/conf.d/pinnwand.conf
    backup: true
    mode: "0644"
  notify:
    - Reload httpd webserver
...
